<a href="https://colab.research.google.com/github/khushalkumar/pandas-notes/blob/main/pandas_notes_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd

**We'll be learning:**

sorting

basic operations

concat

merging

imdb dataset

In [6]:
!gdown 16CrkzkcNs_gyeAu26lNqgHxX1Vo3VKDP

Downloading...
From: https://drive.google.com/uc?id=16CrkzkcNs_gyeAu26lNqgHxX1Vo3VKDP
To: /content/gapminder.csv
100% 83.8k/83.8k [00:00<00:00, 60.5MB/s]

In [7]:
df = pd.read_csv('/content/gapminder.csv')

**ufuncs: universal functions:**

In [8]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.describe() # To find the details of a df, we ues this.

             year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

What if we want to find these details (mean, sum, count etc.) for an individual column?

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df['life_exp'].sum() # sum of all values in the label life_exp

101344.44467999999

In [ ]:
df['life_exp'].mean()

59.474439366197174

In [ ]:
df['life_exp'].max()

82.603

In [ ]:
df['life_exp'].min()

23.599

In [ ]:
df['life_exp'].count() # gives the answer to 'how many entries?'

1704

**Test your knowledge:**

In [ ]:
# Try creating new columns with values that are the sum of each row. Likewise for other functions.

In [ ]:
df2 = df[['year', 'population', 'life_exp']]

In [ ]:
df2

      year  population  life_exp
0     1952     8425333    28.801
1     1957     9240934    30.332
2     1962    10267083    31.997
3     1967    11537966    34.020
4     1972    13079460    36.088
...    ...         ...       ...
1699  1987     9216418    62.351
1700  1992    10704340    60.377
1701  1997    11404948    46.809
1702  2002    11926563    39.989
1703  2007    12311143    43.487

[1704 rows x 3 columns]

**Sorting**

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.sort_values(['year']) # Default is ascending = True

                 country  year  population continent  life_exp       gdp_cap
0            Afghanistan  1952     8425333      Asia    28.801    779.445314
528               France  1952    42459667    Europe    67.410   7029.809327
540                Gabon  1952      420702    Africa    37.003   4293.476475
1656  West Bank and Gaza  1952     1030585      Asia    43.160   1515.592329
552               Gambia  1952      284320    Africa    30.000    485.230659
...                  ...   ...         ...       ...       ...           ...
1127               Niger  2007    12894865    Africa    56.867    619.676892
1139             Nigeria  2007   135031164    Africa    46.859   2013.977305
1151              Norway  2007     4627926    Europe    80.196  49357.190170
1175            Pakistan  2007   169270617      Asia    65.483   2605.947580
1703            Zimbabwe  2007    12311143    Africa    43.487    469.709298

[1704 rows x 6 columns]

In [ ]:
df.sort_values(['year'], ascending = False)

                country  year  population continent  life_exp        gdp_cap
1703           Zimbabwe  2007    12311143    Africa    43.487     469.709298
491   Equatorial Guinea  2007      551201    Africa    51.579   12154.089750
515            Ethiopia  2007    76511887    Africa    52.947     690.805576
527             Finland  2007     5238460    Europe    79.313   33207.084400
539              France  2007    61083916    Europe    80.657   30470.016700
...                 ...   ...         ...       ...       ...            ...
1116              Niger  1952     3379468    Africa    37.444     761.879376
1128            Nigeria  1952    33119096    Africa    36.324    1077.281856
1140             Norway  1952     3327728    Europe    72.670   10095.421720
1152               Oman  1952      507833      Asia    37.578    1828.230307
852              Kuwait  1952      160000      Asia    55.565  108382.352900

[1704 rows x 6 columns]

In [ ]:
df.sort_values(['year', 'life_exp']).head(20) # First, sort based on 'year' and within that, sort based on life_exp.

,country,year,population,continent,life_exp,gdp_cap
0,Afghanistan,1952,8425333,Asia,28.801,779.445314
552,Gambia,1952,284320,Africa,30.000,485.230659
36,Angola,1952,4232095,Africa,30.015,3520.610273
1344,Sierra Leone,1952,2143249,Africa,30.331,879.787736
1032,Mozambique,1952,6446316,Africa,31.286,468.526038
192,Burkina Faso,1952,4469979,Africa,31.975,543.255241
624,Guinea-Bissau,1952,580653,Africa,32.500,299.850319
1668,"Yemen, Rep.",1952,4963829,Asia,32.548,781.717576
1392,Somalia,1952,2526994,Africa,32.978,1135.749842
612,Guinea,1952,2664249,Africa,33.609,510.196492
948,Mali,1952,3838168,Africa,33.685,452.336981
504,Ethiopia,1952,20860941,Africa,34.078,362.146280
480,Equatorial Guinea,1952,216964,Africa,34.482,375.643123
420,Djibouti,1952,63149,Africa,34.812,2669.529475
252,Central African Republic,1952,1291695,Africa,35.463,1071.310713
492,Eritrea,1952,1438760,Africa,35.928,328.940557
1068,Nepal,1952,9182536,Asia,36.157,545.865723
924,Malawi,1952,2917802,Africa,36.256,369.165080
1044,Myanmar,1952,20092996,Asia,36.319,331.000000
1128,Nigeria,1952,33119096,Africa,36.324,1077.281856

In [ ]:
df.sort_values(['year', 'life_exp'], ascending = False).head(20)

               country  year  population continent  life_exp      gdp_cap
803              Japan  2007   127467972      Asia    82.603  31656.06806
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.97867
695            Iceland  2007      301931    Europe    81.757  36180.78919
1487       Switzerland  2007     7554661    Europe    81.701  37506.41907
71           Australia  2007    20434176   Oceania    81.235  34435.36744
1427             Spain  2007    40448191    Europe    80.941  28821.06370
1475            Sweden  2007     9031088    Europe    80.884  33859.74835
767             Israel  2007     6426679      Asia    80.745  25523.27710
539             France  2007    61083916    Europe    80.657  30470.01670
251             Canada  2007    33390141  Americas    80.653  36319.23501
779              Italy  2007    58147733    Europe    80.546  28569.71970
1103       New Zealand  2007     4115771   Oceania    80.204  25185.00911
1151            Norway  2007     4627926    Europe    80.196  49357.19017
1367         Singapore  2007     4553009      Asia    79.972  47143.17964
83             Austria  2007     8199783    Europe    79.829  36126.49270
1091       Netherlands  2007    16570613    Europe    79.762  36797.93332
599             Greece  2007    10706290    Europe    79.483  27538.41188
119            Belgium  2007    10392226    Europe    79.441  33692.60508
1607    United Kingdom  2007    60776238    Europe    79.425  33203.26128
575            Germany  2007    82400996    Europe    79.406  32170.37442

In [ ]:
df2 = df.sort_values(['year', 'life_exp'], ascending = [True, False])
df2

           country  year  population continent  life_exp       gdp_cap
1463     Swaziland  2007     1133066    Africa    39.613   4513.480643
1043    Mozambique  2007    19951656    Africa    42.082    823.685621
1691        Zambia  2007    11746035    Africa    42.384   1271.211593
1355  Sierra Leone  2007     6144562    Africa    42.568    862.540756
887        Lesotho  2007     2012649    Africa    42.592   1569.331442
...            ...   ...         ...       ...       ...           ...
408        Denmark  1952     4334000    Europe    70.780   9692.385245
1464        Sweden  1952     7124673    Europe    71.860   8527.844662
1080   Netherlands  1952    10381988    Europe    72.130   8941.571858
684        Iceland  1952      147962    Europe    72.490   7267.688428
1140        Norway  1952     3327728    Europe    72.670  10095.421720

[1704 rows x 6 columns]

In [ ]:
df2 = df.sort_values(['country','life_exp'], ascending = [False, True]) # lexicographical sort for country.
df2

          country  year  population continent  life_exp     gdp_cap
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1692     Zimbabwe  1952     3080907    Africa    48.451  406.884115
1693     Zimbabwe  1957     3646340    Africa    50.469  518.764268
...           ...   ...         ...       ...       ...         ...
7     Afghanistan  1987    13867957      Asia    40.822  852.395945
8     Afghanistan  1992    16317921      Asia    41.674  649.341395
9     Afghanistan  1997    22227415      Asia    41.763  635.341351
10    Afghanistan  2002    25268405      Asia    42.129  726.734055
11    Afghanistan  2007    31889923      Asia    43.828  974.580338

[1704 rows x 6 columns]

**Concatenating:**

In [ ]:
x = pd.DataFrame({'A': [10, 30], 'B': [20, 40]}) # Creating a df
y = pd.DataFrame({'A': [10, 30, 100], 'C': [20, 40, 100], 'D': [200, 200, 300]})
x

    A   B
0  10  20
1  30  40

In [ ]:
y

     A    C    D
0   10   20  200
1   30   40  200
2  100  100  300

axis = 0, vertical direction. Imagine boxes on top of one another. 

Comparison of columns is done here.

In [ ]:
df4 = pd.concat([x,y]) # concatenating with axis = 0 as default.
df4 # Notice the indexing is not uniform. It is explicit. Let's make it implicit.

     A     B      C      D
0   10  20.0    NaN    NaN
1   30  40.0    NaN    NaN
0   10   NaN   20.0  200.0
1   30   NaN   40.0  200.0
2  100   NaN  100.0  300.0

In [ ]:
df4 = pd.concat([x,y], ignore_index = True) # making index implicit.
df4

     A     B      C      D
0   10  20.0    NaN    NaN
1   30  40.0    NaN    NaN
2   10   NaN   20.0  200.0
3   30   NaN   40.0  200.0
4  100   NaN  100.0  300.0

In [ ]:
df4.info() # columns B C and D are float because NaN is float type.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       2 non-null      float64
 2   C       3 non-null      float64
 3   D       3 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 288.0 bytes

axis = 1, horizontal direction.

Comparison of indexes is done here.

In [ ]:
pd.concat([x,y], axis = 1)

      A     B    A    C    D
0  10.0  20.0   10   20  200
1  30.0  40.0   30   40  200
2   NaN   NaN  100  100  300

**Merge:**

concat: stack multiple df along 0/1 axis.

merging: combines df in smarter way based on values of columns.

![image.png]()

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
users = pd.DataFrame({'userid': [1,2,3], 'name': ["sarath","shahid","khushal"]})

In [ ]:
users

   userid     name
0       1   sarath
1       2   shahid
2       3  khushal

In [ ]:
msgs = pd.DataFrame({'userid': [1,1,2,4], 'msg': ['hmm', 'accha', 'theek hai', 'nice']})

In [ ]:
msgs

   userid        msg
0       1        hmm
1       1      accha
2       2  theek hai
3       4       nice

In [ ]:
users.merge(msgs, on = 'userid') # default 'how' for merge is inner.

   userid    name        msg
0       1  sarath        hmm
1       1  sarath      accha
2       2  shahid  theek hai

In [ ]:
users.merge(msgs, on = "userid", how = "outer") # outer merge.

   userid     name        msg
0       1   sarath        hmm
1       1   sarath      accha
2       2   shahid  theek hai
3       3  khushal        NaN
4       4      NaN       nice

In [ ]:
users.merge(msgs, on = "userid", how = "left")

   userid     name        msg
0       1   sarath        hmm
1       1   sarath      accha
2       2   shahid  theek hai
3       3  khushal        NaN

In [ ]:
users.merge(msgs, on = 'userid' ,how = "right")

   userid    name        msg
0       1  sarath        hmm
1       1  sarath      accha
2       2  shahid  theek hai
3       4     NaN       nice

if the two dataframes don't have a similar named column:

In [ ]:
users.rename(columns = {'userid': 'id'}, inplace = True) # changing userid label to id.

In [ ]:
msgs

   userid        msg
0       1        hmm
1       1      accha
2       2  theek hai
3       4       nice

In [ ]:
users

   id     name
0   1   sarath
1   2   shahid
2   3  khushal

In [ ]:
users.merge(msgs, left_on = "id", right_on = 'userid') # two columns with similar elements appear.
# Later on, we can drop one of these columns.

   id    name  userid        msg
0   1  sarath       1        hmm
1   1  sarath       1      accha
2   2  shahid       2  theek hai

In [ ]:
users = pd.DataFrame({'id': [3,2,1], 'name': ["sarath","shahid","khushal"]})

In [ ]:
msgs = pd.DataFrame({'userid': [1,1,2,4], 'msg': ['hmm', 'accha', 'theek hai', 'nice']})

In [ ]:
users

   id     name
0   3   sarath
1   2   shahid
2   1  khushal

In [ ]:
msgs

   userid        msg
0       1        hmm
1       1      accha
2       2  theek hai
3       4       nice

In [ ]:
users.merge(msgs, left_on = 'id', right_on = 'userid') # inner join

   id     name  userid        msg
0   2   shahid       2  theek hai
1   1  khushal       1        hmm
2   1  khushal       1      accha

# imdb dataset

In [ ]:
!gdown 1A3wwnIZYaAvLeK4UUuC30X5IdaOq-nmy

Downloading...
From: https://drive.google.com/uc?id=1A3wwnIZYaAvLeK4UUuC30X5IdaOq-nmy
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 65.5MB/s]

In [ ]:
!gdown 1R5o_yCY76YNsD0f10ZVgZpxtrYY78PCJ

Downloading...
From: https://drive.google.com/uc?id=1R5o_yCY76YNsD0f10ZVgZpxtrYY78PCJ
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 73.6MB/s]

In [ ]:
directors = pd.read_csv("/content/directors.csv")
directors

      Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [ ]:
directors = pd.read_csv("/content/directors.csv", index_col = 0) # Set 0th column from csv as index.
directors

          director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

In [ ]:
movies = pd.read_csv('/content/movies.csv')
movies

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
1461,4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
1462,4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
1463,4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
1464,4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [ ]:
movies = pd.read_csv('/content/movies.csv', index_col = 0)
movies

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [ ]:
directors

          director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

**merge the columns based on director id:**

In [ ]:
#movies.merge(directors, left_on = 'director_id', right_on = 'id', ) # which join to use?

First, let's check if all director names in 'movies' are also available in 'directors':

In [ ]:
import numpy as np

In [ ]:
movies['director_id'].isin(directors['id']) # These are individual values. We want one final bool val.

0       True
1       True
2       True
3       True
5       True
        ...
4736    True
4743    True
4748    True
4749    True
4768    True
Name: director_id, Length: 1465, dtype: bool

In [ ]:
np.all(movies['director_id'].isin(directors['id'])) # Checks all values and gives the output.

True

Now, we can merge:

In [ ]:
data = movies.merge(directors, left_on = 'director_id', right_on = 'id', how = 'inner') # left will work the same.

How conflicting column names are handled:

In [ ]:
data # both dataframes had a column labeled 'id'. Hence, the id from left df while merging becomes id_x and from right df, id_y.

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,4762,1997,Nov,Tuesday,James Cameron,4762,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,4762,1991,Jul,Monday,James Cameron,4762,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,4762,1994,Jul,Thursday,James Cameron,4762,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,4762,1989,Aug,Wednesday,James Cameron,4762,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,6204,2013,Sep,Wednesday,Nicole Holofcener,6204,Female
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,6204,2006,Sep,Thursday,Nicole Holofcener,6204,Female
1462,47524,3000000,5,0,Please Give,6.0,57,6204,2010,Jan,Friday,Nicole Holofcener,6204,Female
1463,47962,0,0,0,Walking and Talking,6.6,7,6204,1996,Jul,Wednesday,Nicole Holofcener,6204,Female
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,6204,2001,Aug,Friday,Nicole Holofcener,6204,Female

In [ ]:
data.drop(columns = ['director_id', 'id_y'], inplace = True ) # dropping unwanted id columns.

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_x           1465 non-null   int64
 1   budget         1465 non-null   int64
 2   popularity     1465 non-null   int64
 3   revenue        1465 non-null   int64
 4   title          1465 non-null   object
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64
 7   year           1465 non-null   int64
 8   month          1465 non-null   object
 9   day            1465 non-null   object
 10  director_name  1465 non-null   object
 11  gender         1341 non-null   object
dtypes: float64(1), int64(6), object(5)
memory usage: 148.8+ KB

In [ ]:
data[data['gender'].isnull()] # finding rows with NaN values

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
105,43620,180000000,42,372234864,The Golden Compass,5.8,1303,2007,Dec,Tuesday,Chris Weitz,NaN
106,44495,50000000,94,709827462,The Twilight Saga: New Moon,5.6,2436,2009,Mar,Sunday,Chris Weitz,NaN
107,45166,0,9,0,Down to Earth,4.9,95,2001,Feb,Friday,Chris Weitz,NaN
108,45353,27000000,28,129000000,About a Boy,6.6,607,2002,Apr,Friday,Chris Weitz,NaN
109,46407,11000000,60,235483004,American Pie,6.4,2296,1999,Jul,Friday,Chris Weitz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1450,46727,10000000,2,0,Adam Resurrected,6.4,22,2008,Aug,Friday,Paul Schrader,NaN
1451,46975,7000000,7,2062066,Auto Focus,6.1,56,2002,Oct,Friday,Paul Schrader,NaN
1452,47233,5000000,6,0,Light Sleeper,5.7,15,1992,Aug,Friday,Paul Schrader,NaN
1453,47263,15000000,10,0,Dying of the Light,4.5,118,2014,Dec,Thursday,Paul Schrader,NaN
1454,48244,250000,6,56825,The Canyons,4.1,75,2013,Jul,Monday,Paul Schrader,NaN

In [ ]:
data['director_name'].unique()

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes',
       'Christopher Nolan', 'Sam Raimi', 'Zack Snyder', 'Bryan Singer',
       'Marc Forster', 'Andrew Adamson', 'Rob Marshall',
       'Barry Sonnenfeld', 'Peter Jackson', 'Ridley Scott', 'Chris Weitz',
       'Peter Berg', 'Tim Burton', 'Brett Ratner', 'Michael Bay',
       'Martin Campbell', 'McG', 'James Wan', 'Mike Newell',
       'Guillermo del Toro', 'Steven Spielberg', 'Justin Lin',
       'Roland Emmerich', 'Robert Zemeckis', 'Lilly Wachowski',
       'Jon Favreau', 'Martin Scorsese', 'Rob Cohen', 'David Ayer',
       'Tom Shadyac', 'Doug Liman', 'Kevin Reynolds', 'David Fincher',
       'Francis Lawrence', 'Jon Turteltaub', 'Wolfgang Petersen',
       'Michael Apted', 'Oliver Stone', 'Shawn Levy', 'George Miller',
       'Ron Howard', 'Kenneth Branagh', 'Jonathan Liebesman',
       'M. Night Shyamalan', 'Joe Wright', 'Rob Minkoff', 'Lee Tamahori',
       'Edward Zwick', 'Alex Proyas', 'Richard Donner', 'Ang Lee',
       'Jon M. Chu', 'Bill Condon', 'Louis Leterrier',
       'Alejandro GonzÃ¡lez IÃ±Ã¡rritu', 'Paul Greengrass', 'Phillip Noyce',
       'Darren Aronofsky', 'Chris Columbus', 'Robert Schwentke',
       'Guy Ritchie', 'Paul Verhoeven', 'John McTiernan',
       'Joel Schumacher', 'John Woo', 'Tim Story', 'James Mangold',
       'Roger Donaldson', 'Steven Soderbergh', 'Raja Gosnell',
       'Jan de Bont', 'Frank Coraci', 'Michael Mann', 'Peter Chelsom',
       'Tony Scott', 'Paul Weitz', 'Adam McKay', 'Chuck Russell',
       'Quentin Tarantino', 'Simon West', 'Peter Hyams', 'Tom Tykwer',
       'Zhang Yimou', 'Frank Oz', 'Jay Roach', 'Luc Besson',
       'Mark Waters', 'Renny Harlin', 'Ben Stiller', 'Dennis Dugan',
       'Sydney Pollack', 'Brian De Palma', 'Paul W.S. Anderson',
       'Nancy Meyers', 'Peter Segal', 'George A. Romero', 'Todd Phillips',
       'Gary Winick', 'Adam Shankman', 'Les Mayfield', 'Ivan Reitman',
       'Stephen Hopkins', 'Jonathan Demme', 'Terry Gilliam', 'Joe Dante',
       'John Singleton', 'Mike Nichols', 'F. Gary Gray', 'Antoine Fuqua',
       'Robert Luketic', 'Barry Levinson', 'Andy Tennant', 'Judd Apatow',
       'Garry Marshall', 'Cameron Crowe', 'George Clooney',
       'Andrzej Bartkowiak', 'Bobby Farrelly', 'Lawrence Kasdan',
       'Clint Eastwood', 'Larry Charles', 'Taylor Hackford',
       'Roman Polanski', 'Robert Rodriguez', 'Rob Reiner', 'Tim Hill',
       'Robert Redford', 'Kenny Ortega', 'Brian Robbins', 'Brian Levant',
       'David O. Russell', 'Jean-Pierre Jeunet', 'Harold Ramis',
       'Donald Petrie', 'Joel Coen', 'Rod Lurie', 'David Koepp',
       'Uwe Boll', 'Stephen Herek', 'John Madden', 'Wayne Wang',
       'Francis Ford Coppola', 'Curtis Hanson', 'John Whitesell',
       'Neil Jordan', 'Spike Lee', 'Brian Helgeland',
       'Jaume Collet-Serra', 'Andy Fickman', 'Gary Fleder', 'John Landis',
       'Danny Boyle', 'Andrew Niccol', 'John Carpenter', 'Wes Anderson',
       'David Cronenberg', 'David Gordon Green', 'Richard LaGravenese',
       'Stephen Frears', 'David Zucker', 'David R. Ellis', 'David Lynch',
       'Gus Van Sant', 'John Glen', 'Catherine Hardwicke',
       'Anne Fletcher', 'Wes Craven', 'Nicholas Stoller',
       'Stephen Daldry', 'Malcolm D. Lee', 'Steve Miner',
       'Paul Thomas Anderson', 'Kirk Jones', 'Kevin Smith', 'Scott Hicks',
       'Lasse HallstrÃ¶m', 'Jason Reitman', 'Alexander Payne',
       'Woody Allen', 'Jason Friedberg', "Gavin O'Connor",
       'Miguel Arteta', 'Richard Linklater', 'Michael Winterbottom',
       'Tyler Perry', 'Atom Egoyan', 'Sidney Lumet', 'Mira Nair',
       'Michael Moore', 'Mike Leigh', 'James Ivory', 'Brad Anderson',
       'Michael Polish', 'Paul Schrader', 'Darren Lynn Bousman',
       'Nicole Holofcener'], dtype=object)

In [ ]:
data['director_name'].nunique()

199

In [ ]:
data.shape

(1465, 12)

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
3,43879,115000000,38,378882411,True Lies,6.8,1116,1994,Jul,Thursday,James Cameron,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,46859,0,14,25288872,Enough Said,6.6,348,2013,Sep,Wednesday,Nicole Holofcener,Female
1461,47023,6500000,11,13368437,Friends with Money,5.1,128,2006,Sep,Thursday,Nicole Holofcener,Female
1462,47524,3000000,5,0,Please Give,6.0,57,2010,Jan,Friday,Nicole Holofcener,Female
1463,47962,0,0,0,Walking and Talking,6.6,7,1996,Jul,Wednesday,Nicole Holofcener,Female
1464,48229,250000,1,4186931,Lovely & Amazing,6.3,23,2001,Aug,Friday,Nicole Holofcener,Female

In [ ]:
data[data['vote_average'] >= 7] # masking

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43622,200000000,100,1845034188,Titanic,7.5,7562,1997,Nov,Tuesday,James Cameron,Male
2,43876,100000000,101,520000000,Terminator 2: Judgment Day,7.7,4185,1991,Jul,Monday,James Cameron,Male
4,44184,70000000,24,90000098,The Abyss,7.1,808,1989,Aug,Wednesday,James Cameron,Male
5,46000,18500000,67,183316455,Aliens,7.7,3220,1986,Jul,Friday,James Cameron,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1431,46869,8000000,7,18124262,Another Year,7.0,97,2010,Nov,Friday,Mike Leigh,Male
1433,46168,11500000,15,23237911,The Remains of the Day,7.5,202,1993,Nov,Friday,James Ivory,Male
1438,47597,0,11,0,Maurice,7.1,61,1987,Sep,Friday,James Ivory,Male
1441,47232,5000000,35,8203235,The Machinist,7.3,1247,2004,Feb,Monday,Brad Anderson,Male
1448,48124,0,0,0,Twin Falls Idaho,7.0,11,1999,Jul,Friday,Michael Polish,Male