<a href="https://colab.research.google.com/github/khushalkumar/pandas-notes/blob/main/pandas_notes_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Welcome to Pandas 4!')

Welcome to Pandas 4!

In [ ]:
import pandas as pd
import numpy as np
!gdown 1A3wwnIZYaAvLeK4UUuC30X5IdaOq-nmy
!gdown 1R5o_yCY76YNsD0f10ZVgZpxtrYY78PCJ
movies = pd.read_csv('/content/movies.csv', index_col = 0)
directors = pd.read_csv('/content/directors.csv', index_col = 0)
data = movies.merge(directors, left_on = 'director_id', right_on = 'id', how = 'left')
data.drop(['director_id' ,'id_y'], axis = 1, inplace = True)

Downloading...
From: https://drive.google.com/uc?id=1A3wwnIZYaAvLeK4UUuC30X5IdaOq-nmy
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 53.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1R5o_yCY76YNsD0f10ZVgZpxtrYY78PCJ
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 66.8MB/s]

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_x           1465 non-null   int64
 1   budget         1465 non-null   int64
 2   popularity     1465 non-null   int64
 3   revenue        1465 non-null   int64
 4   title          1465 non-null   object
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64
 7   year           1465 non-null   int64
 8   month          1465 non-null   object
 9   day            1465 non-null   object
 10  director_name  1465 non-null   object
 11  gender         1341 non-null   object
dtypes: float64(1), int64(6), object(5)
memory usage: 148.8+ KB

In [ ]:
data.describe(include = 'all')

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
count,1465.000000,1.465000e+03,1465.000000,1.465000e+03,1465,1465.000000,1465.000000,1465.000000,1465,1465,1465,1341
unique,NaN,NaN,NaN,NaN,1465,NaN,NaN,NaN,12,7,199,2
top,NaN,NaN,NaN,NaN,Avatar,NaN,NaN,NaN,Dec,Friday,Steven Spielberg,Male
freq,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,193,654,26,1309
mean,45225.191126,4.802295e+07,30.855973,1.432539e+08,NaN,6.368191,1146.396587,2002.615017,NaN,NaN,NaN,NaN
std,1189.096396,4.935541e+07,34.845214,2.064918e+08,NaN,0.818033,1578.077438,8.680141,NaN,NaN,NaN,NaN
min,43597.000000,0.000000e+00,0.000000,0.000000e+00,NaN,3.000000,1.000000,1976.000000,NaN,NaN,NaN,NaN
25%,44236.000000,1.400000e+07,11.000000,1.738013e+07,NaN,5.900000,216.000000,1998.000000,NaN,NaN,NaN,NaN
50%,45022.000000,3.300000e+07,23.000000,7.578164e+07,NaN,6.400000,571.000000,2004.000000,NaN,NaN,NaN,NaN
75%,45990.000000,6.600000e+07,41.000000,1.792469e+08,NaN,6.900000,1387.000000,2009.000000,NaN,NaN,NaN,NaN
max,48395.000000,3.800000e+08,724.000000,2.787965e+09,NaN,8.300000,13752.000000,2016.000000,NaN,NaN,NaN,NaN

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

**Let's convert budget and revenue into million dollars to make it more readable:**

In [ ]:
data['budget'] = (data['budget'] / 1000000 ).round(2)
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0.00,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0.00,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0.00,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,0.22,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data['revenue'] = (data['revenue'] / 1000000).round(2)
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0.00,7,0.00,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0.00,3,0.00,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

**Using loc to set a condition and fetch desired columns:**

In [ ]:
data[data['vote_average'] >= 7] # using masking to get selective rows.

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
8,43609,200.00,145,1065.66,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,2006,Jun,Tuesday,Gore Verbinski,Male
14,43616,250.00,120,956.02,The Hobbit: The Battle of the Five Armies,7.1,4760,2014,Dec,Wednesday,Peter Jackson,Male
16,43619,250.00,94,958.40,The Hobbit: The Desolation of Smaug,7.6,4524,2013,Dec,Wednesday,Peter Jackson,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1456,48321,0.01,20,7.00,Eraserhead,7.5,485,1977,Mar,Saturday,David Lynch,Male
1457,48323,0.00,5,0.00,The Mighty,7.1,51,1998,Oct,Friday,Peter Chelsom,Male
1458,48335,0.06,27,3.22,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male

In [ ]:
data.loc[data['vote_average'] >= 7] # using loc gives the same result.

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
8,43609,200.00,145,1065.66,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,2006,Jun,Tuesday,Gore Verbinski,Male
14,43616,250.00,120,956.02,The Hobbit: The Battle of the Five Armies,7.1,4760,2014,Dec,Wednesday,Peter Jackson,Male
16,43619,250.00,94,958.40,The Hobbit: The Desolation of Smaug,7.6,4524,2013,Dec,Wednesday,Peter Jackson,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1456,48321,0.01,20,7.00,Eraserhead,7.5,485,1977,Mar,Saturday,David Lynch,Male
1457,48323,0.00,5,0.00,The Mighty,7.1,51,1998,Oct,Friday,Peter Chelsom,Male
1458,48335,0.06,27,3.22,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male

filtering dataset and then selecting columns - two steps involved.

In [ ]:
data[data['vote_average'] >= 7][['title', 'director_name']] # going one step further, accessing desired columns

                                           title      director_name
0                                         Avatar      James Cameron
3                          The Dark Knight Rises  Christopher Nolan
8     Pirates of the Caribbean: Dead Man's Chest     Gore Verbinski
14     The Hobbit: The Battle of the Five Armies      Peter Jackson
16           The Hobbit: The Desolation of Smaug      Peter Jackson
...                                          ...                ...
1456                                  Eraserhead        David Lynch
1457                                  The Mighty      Peter Chelsom
1458                                          Pi   Darren Aronofsky
1460                              The Last Waltz    Martin Scorsese
1461                                      Clerks        Kevin Smith

[363 rows x 2 columns]

Taking the rows where a condition is satisfied and explicitly giving the column names:

df.loc(filterd rows, selected cols) - only one step involved.

In [ ]:
data.loc[data['vote_average'] >= 7, ['title', 'director_name']] # using loc to access desired columns.

                                           title      director_name
0                                         Avatar      James Cameron
3                          The Dark Knight Rises  Christopher Nolan
8     Pirates of the Caribbean: Dead Man's Chest     Gore Verbinski
14     The Hobbit: The Battle of the Five Armies      Peter Jackson
16           The Hobbit: The Desolation of Smaug      Peter Jackson
...                                          ...                ...
1456                                  Eraserhead        David Lynch
1457                                  The Mighty      Peter Chelsom
1458                                          Pi   Darren Aronofsky
1460                              The Last Waltz    Martin Scorsese
1461                                      Clerks        Kevin Smith

[363 rows x 2 columns]

In [ ]:
data.loc[ (data['vote_average'] >= 7) & (data['year'] >= 2015) ] # providing two conditions.

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
30,43641,190.0,102,1506.25,Furious 7,7.3,4176,2015,Apr,Wednesday,James Wan,Male
78,43724,150.0,434,378.86,Mad Max: Fury Road,7.2,9427,2015,May,Wednesday,George Miller,Male
106,43773,135.0,100,532.95,The Revenant,7.3,6396,2015,Dec,Friday,Alejandro González Iñárritu,Male
162,43867,108.0,167,630.16,The Martian,7.6,7268,2015,Sep,Wednesday,Ridley Scott,Male
312,44128,75.0,48,108.15,The Man from U.N.C.L.E.,7.1,2265,2015,Aug,Thursday,Guy Ritchie,Male
394,44281,44.0,68,155.76,The Hateful Eight,7.6,4274,2015,Dec,Friday,Quentin Tarantino,Male
519,44538,50.0,42,69.41,13 Hours: The Secret Soldiers of Benghazi,7.0,938,2016,Jan,Wednesday,Michael Bay,Male
617,44757,40.0,68,320.17,The Conjuring 2,7.0,1949,2016,May,Friday,James Wan,Male
625,44770,35.0,53,194.56,The Intern,7.1,1881,2015,Sep,Thursday,Nancy Meyers,Female
635,44784,40.0,48,165.48,Bridge of Spies,7.2,2583,2015,Oct,Thursday,Steven Spielberg,Male
808,45194,30.0,65,91.71,Southpaw,7.3,2067,2015,Jun,Monday,Antoine Fuqua,Male
833,45293,28.0,61,201.63,Straight Outta Compton,7.7,1355,2015,Aug,Thursday,F. Gary Gray,Male
839,45301,28.0,57,133.35,The Big Short,7.3,2607,2015,Dec,Friday,Adam McKay,Male
1344,47181,5.0,22,24.80,Race,7.1,478,2016,Feb,Friday,Stephen Hopkins,Male

**Get the title of those movies that have ratings >= 7 and were released in/after 2015:**

In [ ]:
data.loc[(data['vote_average'] >= 7) & (data['year'] >= 2015), ['title']] # this gives pandas df.

                                          title
30                                    Furious 7
78                           Mad Max: Fury Road
106                                The Revenant
162                                 The Martian
312                     The Man from U.N.C.L.E.
394                           The Hateful Eight
519   13 Hours: The Secret Soldiers of Benghazi
617                             The Conjuring 2
625                                  The Intern
635                             Bridge of Spies
808                                    Southpaw
833                      Straight Outta Compton
839                               The Big Short
1344                                       Race

In [ ]:
data.loc[(data['vote_average'] >= 7) & (data['year'] >= 2015), 'title'] # this gives series.

30                                      Furious 7
78                             Mad Max: Fury Road
106                                  The Revenant
162                                   The Martian
312                       The Man from U.N.C.L.E.
394                             The Hateful Eight
519     13 Hours: The Secret Soldiers of Benghazi
617                               The Conjuring 2
625                                    The Intern
635                               Bridge of Spies
808                                      Southpaw
833                        Straight Outta Compton
839                                 The Big Short
1344                                         Race
Name: title, dtype: object

**Fetch movies which were released on either Friday or Saturday:**

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0.00,7,0.00,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0.00,3,0.00,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data.loc[(data['day'] == 'Friday') | (data['day'] == 'Saturday')]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
12,43614,380.00,135,1045.71,Pirates of the Caribbean: On Stranger Tides,6.4,4948,2011,May,Saturday,Rob Marshall,Male
22,43627,200.00,35,783.77,Spider-Man 2,6.7,4321,2004,Jun,Friday,Sam Raimi,Male
25,43632,150.00,21,836.30,Transformers: Revenge of the Fallen,6.0,3138,2009,Jun,Friday,Michael Bay,Male
40,43656,200.00,45,769.65,2012,5.6,4903,2009,Oct,Saturday,Roland Emmerich,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1457,48323,0.00,5,0.00,The Mighty,7.1,51,1998,Oct,Friday,Peter Chelsom,Male
1458,48335,0.06,27,3.22,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1462,48375,0.00,7,0.00,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0.00,3,0.00,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data.loc[(data['day'] == 'Friday') | (data['day'] == 'Saturday'), ['title']] # filtering the movie names

                                            title
1        Pirates of the Caribbean: At World's End
12    Pirates of the Caribbean: On Stranger Tides
22                                   Spider-Man 2
25            Transformers: Revenge of the Fallen
40                                           2012
...                                           ...
1457                                   The Mighty
1458                                           Pi
1462                                      Rampage
1463                                      Slacker
1464                                  El Mariachi

[701 rows x 1 columns]

fetch movies which are highly rated (>= 7 rating), latest (>= 2015) and released in the last quarter (oct, nov, dec):

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0.00,7,0.00,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0.00,3,0.00,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
(data['vote_average'] >= 7) & (data['year'] >= 2015) & ((data['month'] == 'Oct') | (data['month'] == 'Nov') | (data['month'] == 'Dec')) # mask

0       False
1       False
2       False
3       False
4       False
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Length: 1465, dtype: bool

In [ ]:
data[ (data['vote_average'] >= 7) & (data['year'] >= 2015) & ((data['month'] == 'Oct') | (data['month'] == 'Nov') | (data['month'] == 'Dec'))]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
106,43773,135.0,100,532.95,The Revenant,7.3,6396,2015,Dec,Friday,Alejandro González Iñárritu,Male
394,44281,44.0,68,155.76,The Hateful Eight,7.6,4274,2015,Dec,Friday,Quentin Tarantino,Male
635,44784,40.0,48,165.48,Bridge of Spies,7.2,2583,2015,Oct,Thursday,Steven Spielberg,Male
839,45301,28.0,57,133.35,The Big Short,7.3,2607,2015,Dec,Friday,Adam McKay,Male

In [ ]:
data['month'].isin(['Oct','Nov','Dec']) # another way to do the mask for months.

0        True
1       False
2        True
3       False
4       False
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Name: month, Length: 1465, dtype: bool

In [ ]:
data.loc[data['month'].isin(['Oct','Nov','Dec'])]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
7,43608,200.00,107,586.09,Quantum of Solace,6.1,2965,2008,Oct,Thursday,Marc Forster,Male
14,43616,250.00,120,956.02,The Hobbit: The Battle of the Five Armies,7.1,4760,2014,Dec,Wednesday,Peter Jackson,Male
16,43619,250.00,94,958.40,The Hobbit: The Desolation of Smaug,7.6,4524,2013,Dec,Wednesday,Peter Jackson,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1451,48268,0.20,13,4.51,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,Male
1452,48274,0.00,5,2.61,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,Male
1454,48300,0.15,8,2.89,Tadpole,5.5,19,2002,Nov,Friday,Gary Winick,Male
1457,48323,0.00,5,0.00,The Mighty,7.1,51,1998,Oct,Friday,Peter Chelsom,Male
1459,48359,0.00,2,0.00,George Washington,6.4,36,2000,Oct,Sunday,David Gordon Green,Male

In [ ]:
data.loc[(data['vote_average'] >= 7) & (data['year'] >= 2015) & (data['month'].isin(['Oct', 'Nov', 'Dec']))] # putting it all together

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
106,43773,135.0,100,532.95,The Revenant,7.3,6396,2015,Dec,Friday,Alejandro González Iñárritu,Male
394,44281,44.0,68,155.76,The Hateful Eight,7.6,4274,2015,Dec,Friday,Quentin Tarantino,Male
635,44784,40.0,48,165.48,Bridge of Spies,7.2,2583,2015,Oct,Thursday,Steven Spielberg,Male
839,45301,28.0,57,133.35,The Big Short,7.3,2607,2015,Dec,Friday,Adam McKay,Male

**Using condition  with a string (object type):**

In [ ]:
data.loc[data['title'] < 'Avengers'] # comparing lexicographically.

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.0,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
23,43629,200.0,78,1025.49,Alice in Wonderland,6.4,4645,2010,Mar,Wednesday,Tim Burton,Male
40,43656,200.0,45,769.65,2012,5.6,4903,2009,Oct,Saturday,Roland Emmerich,Male
41,43657,200.0,39,325.23,A Christmas Carol,6.6,1095,2009,Nov,Wednesday,Robert Zemeckis,Male
69,43709,155.0,39,167.30,Alexander,5.6,927,2004,Nov,Sunday,Oliver Stone,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1390,47491,3.0,7,20.97,A Room with a View,6.9,156,1985,Dec,Friday,James Ivory,Male
1395,47575,3.0,3,0.00,Amnesiac,4.1,52,2015,Aug,Friday,Michael Polish,Male
1405,47686,2.0,23,20.91,Amores perros,7.6,521,2000,Jun,Friday,Alejandro González Iñárritu,Male
1432,47970,0.0,3,0.00,All the Real Girls,5.9,30,2003,Aug,Friday,David Gordon Green,Male
1440,48155,0.0,0,0.00,Alleluia! The Devil's Carnival,6.0,2,2016,Mar,Tuesday,Darren Lynn Bousman,Male

**String methods can be used with pandas:**

In [ ]:
data['title'].str.contains('The')

0       False
1       False
2       False
3        True
4       False
        ...
1460     True
1461    False
1462    False
1463    False
1464    False
Name: title, Length: 1465, dtype: bool

In [ ]:
type(data['title'].str.contains('The'))

pandas.core.series.Series

In [ ]:
data.loc[data['title'].str.contains('The')] # It's getting T/F values

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
9,43610,255.00,49,89.29,The Lone Ranger,5.9,2311,2013,Jul,Wednesday,Gore Verbinski,Male
11,43612,225.00,53,419.65,The Chronicles of Narnia: Prince Caspian,6.3,1630,2008,May,Thursday,Andrew Adamson,Male
14,43616,250.00,120,956.02,The Hobbit: The Battle of the Five Armies,7.1,4760,2014,Dec,Wednesday,Peter Jackson,Male
16,43619,250.00,94,958.40,The Hobbit: The Desolation of Smaug,7.6,4524,2013,Dec,Wednesday,Peter Jackson,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1440,48155,0.00,0,0.00,Alleluia! The Devil's Carnival,6.0,2,2016,Mar,Tuesday,Darren Lynn Bousman,Male
1443,48192,0.35,35,29.40,The Evil Dead,7.3,894,1981,Oct,Thursday,Sam Raimi,Male
1449,48244,0.25,6,0.06,The Canyons,4.1,75,2013,Jul,Monday,Paul Schrader,NaN
1457,48323,0.00,5,0.00,The Mighty,7.1,51,1998,Oct,Friday,Peter Chelsom,Male
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male

In [ ]:
data.loc[data['title'].str.contains('The', case = False)] # case doesn't matter here.

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
8,43609,200.00,145,1065.66,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,2006,Jun,Tuesday,Gore Verbinski,Male
9,43610,255.00,49,89.29,The Lone Ranger,5.9,2311,2013,Jul,Wednesday,Gore Verbinski,Male
11,43612,225.00,53,419.65,The Chronicles of Narnia: Prince Caspian,6.3,1630,2008,May,Thursday,Andrew Adamson,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1440,48155,0.00,0,0.00,Alleluia! The Devil's Carnival,6.0,2,2016,Mar,Tuesday,Darren Lynn Bousman,Male
1443,48192,0.35,35,29.40,The Evil Dead,7.3,894,1981,Oct,Thursday,Sam Raimi,Male
1449,48244,0.25,6,0.06,The Canyons,4.1,75,2013,Jul,Monday,Paul Schrader,NaN
1457,48323,0.00,5,0.00,The Mighty,7.1,51,1998,Oct,Friday,Peter Chelsom,Male
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male

In [ ]:
data.loc[data['title'].str.startswith('Batman')]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
5,43606,250.0,155,873.26,Batman v Superman: Dawn of Justice,5.7,7004,2016,Mar,Wednesday,Zack Snyder,Male
74,43716,150.0,115,374.22,Batman Begins,7.5,7359,2005,Jun,Friday,Christopher Nolan,Male
128,43807,125.0,50,238.21,Batman & Robin,4.2,1418,1997,Jun,Friday,Joel Schumacher,Male
184,43896,100.0,48,336.53,Batman Forever,5.2,1498,1995,May,Wednesday,Joel Schumacher,Male
257,44025,80.0,59,280.00,Batman Returns,6.6,1673,1992,Jun,Friday,Tim Burton,Male
704,44956,35.0,44,411.35,Batman,7.0,2096,1989,Jun,Friday,Tim Burton,Male

find top 10 popular movies.

In [ ]:
top_10_popular_movies = data.sort_values('popularity', ascending= False)
top_10_popular_movies.loc[:, ['title']]

                                                  title
58                                         Interstellar
78                                   Mad Max: Fury Road
119   Pirates of the Caribbean: The Curse of the Bla...
120               The Hunger Games: Mockingjay - Part 1
45                                      The Dark Knight
...                                                 ...
1437                                 Finishing The Game
1448                                       Chuck & Buck
1438                            Everything Put Together
1378                               An Everlasting Piece
1440                     Alleluia! The Devil's Carnival

[1465 rows x 1 columns]

In [ ]:
top_10_popular_movies['title']

58                                           Interstellar
78                                     Mad Max: Fury Road
119     Pirates of the Caribbean: The Curse of the Bla...
120                 The Hunger Games: Mockingjay - Part 1
45                                        The Dark Knight
                              ...
1437                                   Finishing The Game
1448                                         Chuck & Buck
1438                              Everything Put Together
1378                                 An Everlasting Piece
1440                       Alleluia! The Devil's Carnival
Name: title, Length: 1465, dtype: object

In [ ]:
data.sort_values(['popularity'], ascending = False)['title'] # We generally don't do this.

58                                           Interstellar
78                                     Mad Max: Fury Road
119     Pirates of the Caribbean: The Curse of the Bla...
120                 The Hunger Games: Mockingjay - Part 1
45                                        The Dark Knight
                              ...
1437                                   Finishing The Game
1448                                         Chuck & Buck
1438                              Everything Put Together
1378                                 An Everlasting Piece
1440                       Alleluia! The Devil's Carnival
Name: title, Length: 1465, dtype: object

In [ ]:
data.sort_values(['popularity'], ascending = False)[['title']] # getting a df. Above statement gave a series.

                                                  title
58                                         Interstellar
78                                   Mad Max: Fury Road
119   Pirates of the Caribbean: The Curse of the Bla...
120               The Hunger Games: Mockingjay - Part 1
45                                      The Dark Knight
...                                                 ...
1437                                 Finishing The Game
1448                                       Chuck & Buck
1438                            Everything Put Together
1378                               An Everlasting Piece
1440                     Alleluia! The Devil's Carnival

[1465 rows x 1 columns]

In [ ]:
type(data.sort_values(['popularity'], ascending = False)) # above statement returns a dataframe.

pandas.core.frame.DataFrame

In [ ]:
# in the rows, we must give boolean values. Below code is not gonna work.
data.loc[data.sort_values(['popularity'], ascending = False), ['title']]  # it'll give error.

NameError: ignored

Fetch all movies by Christopher Nolan:

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0.00,7,0.00,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0.00,3,0.00,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data.loc[data['director_name'] == "Christopher Nolan", ['title']]

                      title
3     The Dark Knight Rises
45          The Dark Knight
58             Interstellar
59                Inception
74            Batman Begins
565                Insomnia
641            The Prestige
1341                Memento

In [ ]:
data['director_name'].value_counts()

Steven Spielberg      26
Martin Scorsese       19
Clint Eastwood        19
Woody Allen           18
Ridley Scott          16
                      ..
Tim Hill               5
Jonathan Liebesman     5
Roman Polanski         5
Larry Charles          5
Nicole Holofcener      5
Name: director_name, Length: 199, dtype: int64

In [ ]:
type(data['director_name'].value_counts()) # it returns a series.

pandas.core.series.Series

In [ ]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1461,48370,0.03,19,3.15,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,Male
1462,48375,0.00,7,0.00,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0.00,3,0.00,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data.loc['director_name'].value_counts() # This doesn’t work cuz .loc expects both rows and columns.
#we are only providing column name, essentially one dimension.

KeyError: ignored

In [ ]:
data['director_name'].value_counts()[['Christopher Nolan']]

Christopher Nolan    8
Name: director_name, dtype: int64

# groupby:

![image.png]()

In [ ]:
data.groupby('director_name') #splitting happens at this step.

In [ ]:
data.groupby('director_name')['budget'] # selecting budget column.

**max budget movie for each director:**

In [ ]:
data.groupby('director_name')['budget'].max() # applying max on each group.

director_name
Adam McKay                     100.0
Adam Shankman                   80.0
Alejandro González Iñárritu    135.0
Alex Proyas                    140.0
Alexander Payne                 30.0
                               ...
Wes Craven                      40.0
Wolfgang Petersen              175.0
Woody Allen                     30.0
Zack Snyder                    250.0
Zhang Yimou                     94.0
Name: budget, Length: 199, dtype: float64

In [ ]:
max_Bud = data.groupby('director_name')['budget'].max()
print(max_Bud.index) # notice how on grouping, the column values become the indexes.

Index(['Adam McKay', 'Adam Shankman', 'Alejandro González Iñárritu',
       'Alex Proyas', 'Alexander Payne', 'Andrew Adamson', 'Andrew Niccol',
       'Andrzej Bartkowiak', 'Andy Fickman', 'Andy Tennant',
       ...
       'Tony Scott', 'Tyler Perry', 'Uwe Boll', 'Wayne Wang', 'Wes Anderson',
       'Wes Craven', 'Wolfgang Petersen', 'Woody Allen', 'Zack Snyder',
       'Zhang Yimou'],
      dtype='object', name='director_name', length=199)

Number of movies for each director:

In [ ]:
data.groupby('director_name')['title'].count()

director_name
Adam McKay                      6
Adam Shankman                   8
Alejandro González Iñárritu     6
Alex Proyas                     5
Alexander Payne                 5
                               ..
Wes Craven                     10
Wolfgang Petersen               7
Woody Allen                    18
Zack Snyder                     7
Zhang Yimou                     6
Name: title, Length: 199, dtype: int64

In [ ]:
data.groupby('director_name')['title'].count().sort_values(ascending = False)

director_name
Steven Spielberg    26
Clint Eastwood      19
Martin Scorsese     19
Woody Allen         18
Robert Rodriguez    16
                    ..
Paul Weitz           5
John Madden          5
Paul Verhoeven       5
John Whitesell       5
Kevin Reynolds       5
Name: title, Length: 199, dtype: int64

In [ ]:
data.groupby('director_name')['year'].min()

director_name
Adam McKay                     2004
Adam Shankman                  2001
Alejandro González Iñárritu    2000
Alex Proyas                    1994
Alexander Payne                1999
                               ...
Wes Craven                     1984
Wolfgang Petersen              1981
Woody Allen                    1977
Zack Snyder                    2004
Zhang Yimou                    2002
Name: year, Length: 199, dtype: int64

In [ ]:
data.groupby('director_name')['year'].max()

director_name
Adam McKay                     2015
Adam Shankman                  2012
Alejandro González Iñárritu    2015
Alex Proyas                    2016
Alexander Payne                2013
                               ...
Wes Craven                     2011
Wolfgang Petersen              2006
Woody Allen                    2013
Zack Snyder                    2016
Zhang Yimou                    2014
Name: year, Length: 199, dtype: int64

**Aggregate: multi indexing**

combining all above functions using aggregate:

In [ ]:
# Applying functions on desired columns. 
df_agg = data.groupby('director_name')[['title', 'year']].aggregate({'title':'count', 'year':['max', 'min']})
df_agg

                            title  year
                            count   max   min
director_name
Adam McKay                      6  2015  2004
Adam Shankman                   8  2012  2001
Alejandro González Iñárritu     6  2015  2000
Alex Proyas                     5  2016  1994
Alexander Payne                 5  2013  1999
...                           ...   ...   ...
Wes Craven                     10  2011  1984
Wolfgang Petersen               7  2006  1981
Woody Allen                    18  2013  1977
Zack Snyder                     7  2016  2004
Zhang Yimou                     6  2014  2002

[199 rows x 3 columns]

what if we just give one function for year in a list?

In [ ]:
df_agg = data.groupby('director_name')[['title', 'year']].aggregate({'title':'count', 'year':['max']})
df_agg

                            title  year
                            count   max
director_name
Adam McKay                      6  2015
Adam Shankman                   8  2012
Alejandro González Iñárritu     6  2015
Alex Proyas                     5  2016
Alexander Payne                 5  2013
...                           ...   ...
Wes Craven                     10  2011
Wolfgang Petersen               7  2006
Woody Allen                    18  2013
Zack Snyder                     7  2016
Zhang Yimou                     6  2014

[199 rows x 2 columns]

What if we give one function for 'year' but not in a list:

In [ ]:
df_agg = data.groupby('director_name')[['title', 'year']].aggregate({'title':'count', 'year':'max'})
df_agg

                             title  year
director_name
Adam McKay                       6  2015
Adam Shankman                    8  2012
Alejandro González Iñárritu      6  2015
Alex Proyas                      5  2016
Alexander Payne                  5  2013
...                            ...   ...
Wes Craven                      10  2011
Wolfgang Petersen                7  2006
Woody Allen                     18  2013
Zack Snyder                      7  2016
Zhang Yimou                      6  2014

[199 rows x 2 columns]

In [ ]:
import numpy as np
df_agg = data.groupby('director_name')[['title', 'year']].aggregate({'title':'count', 'year':[np.min, np.max]}) 
df_agg

                            title  year
                            count  amin  amax
director_name
Adam McKay                      6  2004  2015
Adam Shankman                   8  2001  2012
Alejandro González Iñárritu     6  2000  2015
Alex Proyas                     5  1994  2016
Alexander Payne                 5  1999  2013
...                           ...   ...   ...
Wes Craven                     10  1984  2011
Wolfgang Petersen               7  1981  2006
Woody Allen                    18  1977  2013
Zack Snyder                     7  2004  2016
Zhang Yimou                     6  2002  2014

[199 rows x 3 columns]

In [ ]:
import numpy as np
df_agg = data.groupby('director_name')[['title', 'year']].aggregate({'title':np.max, 'year':[np.min]}) 
df_agg  # why does this not work? If you find an answer, let me know.

                                                          title  year
                                                           amax  amin
director_name
Adam McKay                                       The Other Guys  2004
Adam Shankman                               The Wedding Planner  2001
Alejandro González Iñárritu                        The Revenant  2000
Alex Proyas                                            The Crow  1994
Alexander Payne                                 The Descendants  1999
...                                                         ...   ...
Wes Craven                                  Vampire in Brooklyn  1984
Wolfgang Petersen                                          Troy  1981
Woody Allen                  You Will Meet a Tall Dark Stranger  1977
Zack Snyder                                            Watchmen  2004
Zhang Yimou                                  The Flowers of War  2002

[199 rows x 2 columns]

In [ ]:
df_agg.columns # Notice that the column names are in a list of tuples. multi-index column names.

MultiIndex([('title', 'count'),
            ( 'year',   'max'),
            ( 'year',   'min')],
           )

In [ ]:
df_agg.columns = ['_'.join(col) for col in df_agg.columns] # converting into single indexes.

In [ ]:
df_agg

                             title_count  year_max  year_min
director_name
Adam McKay                             6      2015      2004
Adam Shankman                          8      2012      2001
Alejandro González Iñárritu            6      2015      2000
Alex Proyas                            5      2016      1994
Alexander Payne                        5      2013      1999
...                                  ...       ...       ...
Wes Craven                            10      2011      1984
Wolfgang Petersen                      7      2006      1981
Woody Allen                           18      2013      1977
Zack Snyder                            7      2016      2004
Zhang Yimou                            6      2014      2002

[199 rows x 3 columns]

In [ ]:
df_agg.reset_index(inplace = True) # cuz column names as index doesn't look good.

In [ ]:
df_agg

                   director_name  title_count  year_max  year_min
0                     Adam McKay            6      2015      2004
1                  Adam Shankman            8      2012      2001
2    Alejandro González Iñárritu            6      2015      2000
3                    Alex Proyas            5      2016      1994
4                Alexander Payne            5      2013      1999
..                           ...          ...       ...       ...
194                   Wes Craven           10      2011      1984
195            Wolfgang Petersen            7      2006      1981
196                  Woody Allen           18      2013      1977
197                  Zack Snyder            7      2016      2004
198                  Zhang Yimou            6      2014      2002

[199 rows x 4 columns]

number of years a director has been active:

In [ ]:
df_agg['years_active'] = df_agg['year_max'] - df_agg['year_min']

In [ ]:
df_agg

,director_name,title_count,year_max,year_min,years_active
0,Adam McKay,6,2015,2004,11
1,Adam Shankman,8,2012,2001,11
2,Alejandro González Iñárritu,6,2015,2000,15
3,Alex Proyas,5,2016,1994,22
4,Alexander Payne,5,2013,1999,14
...,...,...,...,...,...
194,Wes Craven,10,2011,1984,27
195,Wolfgang Petersen,7,2006,1981,25
196,Woody Allen,18,2013,1977,36
197,Zack Snyder,7,2016,2004,12
198,Zhang Yimou,6,2014,2002,12

number of movies per year:

In [ ]:
df_agg['movies_per_year'] = (df_agg['title_count']) / (df_agg['years_active'])

In [ ]:
df_agg

,director_name,title_count,year_max,year_min,years_active,movies_per_year
190,Tyler Perry,9,2013,2006,7,1.285714
73,Jason Friedberg,5,2010,2006,4,1.250000
169,Shawn Levy,11,2014,2002,12,0.916667
158,Robert Rodriguez,16,2014,1992,22,0.727273
1,Adam Shankman,8,2012,2001,11,0.727273
...,...,...,...,...,...,...
104,Lawrence Kasdan,5,2012,1985,27,0.185185
109,Luc Besson,5,2014,1985,29,0.172414
157,Robert Redford,5,2010,1980,30,0.166667
170,Sidney Lumet,5,2006,1976,30,0.166667
117,Michael Apted,5,2010,1980,30,0.166667

most productive director:

In [ ]:
df_agg.sort_values("movies_per_year", ascending = False).head(10)

,director_name,title_count,year_max,year_min,years_active,movies_per_year
190,Tyler Perry,9,2013,2006,7,1.285714
73,Jason Friedberg,5,2010,2006,4,1.250000
169,Shawn Levy,11,2014,2002,12,0.916667
158,Robert Rodriguez,16,2014,1992,22,0.727273
1,Adam Shankman,8,2012,2001,11,0.727273
156,Robert Luketic,6,2010,2001,9,0.666667
179,Steven Spielberg,26,2016,1977,39,0.666667
8,Andy Fickman,6,2015,2006,9,0.666667
112,Marc Forster,8,2013,2001,12,0.666667
81,Joel Schumacher,13,2007,1987,20,0.650000

In [ ]:
data.loc[data['budget'] >= 100] # directors who have made a (>= 100) million movie at least once.

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.0,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.0,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.0,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.0,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.0,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
219,43960,100.0,34,235.93,A.I. Artificial Intelligence,6.8,1974,2001,Jun,Friday,Steven Spielberg,Male
229,43972,100.0,24,93.70,Bicentennial Man,6.9,963,1999,Dec,Friday,Chris Columbus,Male
233,43982,100.0,37,384.34,Happy Feet,5.9,1410,2006,Nov,Thursday,George Miller,Male
290,44088,130.0,50,117.83,Pompeii,5.2,1267,2014,Feb,Tuesday,Paul W.S. Anderson,Male
328,44162,150.0,47,919.84,Shrek 2,6.7,2988,2004,May,Wednesday,Andrew Adamson,Male

Find out all the movies of those directors who have created atleast one movie budgeted > 100 million dollars.

![image.png]()

**Explanation:**

x = 'director_name'

max budgeted movie of each director is compared with >= 100.

filter will return T or F.

If returned T, all movies of that director will be included.

If F, all movies of that director will be filtered out.

In [ ]:
# filter is working on the entire sub-group, not a single value.
df_high_budget_dir = data.groupby('director_name').filter(lambda x:x['budget'].max() >= 100)

In [ ]:
df_high_budget_dir

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,0.40,33,100.00,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,Male
1451,48268,0.20,13,4.51,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,Male
1452,48274,0.00,5,2.61,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,Male
1458,48335,0.06,27,3.22,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male

Another way to find movies of high budgeted directors would be:

In [ ]:
high_budget_movies = data.loc[data['budget'] >= 100]
high_budget_movies

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.0,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.0,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.0,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.0,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.0,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
219,43960,100.0,34,235.93,A.I. Artificial Intelligence,6.8,1974,2001,Jun,Friday,Steven Spielberg,Male
229,43972,100.0,24,93.70,Bicentennial Man,6.9,963,1999,Dec,Friday,Chris Columbus,Male
233,43982,100.0,37,384.34,Happy Feet,5.9,1410,2006,Nov,Thursday,George Miller,Male
290,44088,130.0,50,117.83,Pompeii,5.2,1267,2014,Feb,Tuesday,Paul W.S. Anderson,Male
328,44162,150.0,47,919.84,Shrek 2,6.7,2988,2004,May,Wednesday,Andrew Adamson,Male

In [ ]:
unique_high_budget_dir = high_budget_movies['director_name'].unique()
unique_high_budget_dir

array(['James Cameron', 'Gore Verbinski', 'Sam Mendes',
       'Christopher Nolan', 'Sam Raimi', 'Zack Snyder', 'Bryan Singer',
       'Marc Forster', 'Andrew Adamson', 'Rob Marshall',
       'Barry Sonnenfeld', 'Peter Jackson', 'Ridley Scott', 'Chris Weitz',
       'Peter Berg', 'Tim Burton', 'Brett Ratner', 'Michael Bay',
       'Martin Campbell', 'McG', 'James Wan', 'Mike Newell',
       'Guillermo del Toro', 'Steven Spielberg', 'Justin Lin',
       'Roland Emmerich', 'Robert Zemeckis', 'Lilly Wachowski',
       'Jon Favreau', 'Martin Scorsese', 'Rob Cohen', 'David Ayer',
       'Tom Shadyac', 'Doug Liman', 'Kevin Reynolds', 'David Fincher',
       'Francis Lawrence', 'Jon Turteltaub', 'Wolfgang Petersen',
       'Michael Apted', 'Oliver Stone', 'Shawn Levy', 'George Miller',
       'Ron Howard', 'Kenneth Branagh', 'Jonathan Liebesman',
       'M. Night Shyamalan', 'Joe Wright', 'Rob Minkoff', 'Lee Tamahori',
       'Edward Zwick', 'Alex Proyas', 'Richard Donner', 'Ang Lee',
       'Jon M. Chu', 'Bill Condon', 'Louis Leterrier',
       'Alejandro González Iñárritu', 'Phillip Noyce', 'Darren Aronofsky',
       'Chris Columbus', 'Robert Schwentke', 'Guy Ritchie',
       'John McTiernan', 'Joel Schumacher', 'John Woo', 'Tim Story',
       'Paul Greengrass', 'James Mangold', 'Roger Donaldson',
       'Steven Soderbergh', 'Raja Gosnell', 'Jan de Bont', 'Frank Coraci',
       'Michael Mann', 'Tony Scott', 'Paul Weitz', 'Adam McKay',
       'Chuck Russell', 'Quentin Tarantino', 'Simon West', 'Peter Hyams',
       'Paul Verhoeven', 'Tom Tykwer', 'Paul W.S. Anderson'], dtype=object)

In [ ]:
data.loc[data['director_name'].isin(unique_high_budget_dir)]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237.00,150,2787.97,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300.00,139,961.00,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245.00,107,880.67,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250.00,112,1084.94,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258.00,115,890.87,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,0.40,33,100.00,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,Male
1451,48268,0.20,13,4.51,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,Male
1452,48274,0.00,5,2.61,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,Male
1458,48335,0.06,27,3.22,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male

Experienced Directors - Find out details of all the movies where the director has created atleast 15 movies in entire career.

In [ ]:
exp_dir = data.groupby('director_name').filter(lambda x: x['title'].count() >= 15)

In [ ]:
exp_dir

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
15,43618,200.00,37,310.67,Robin Hood,6.2,1398,2010,May,Wednesday,Ridley Scott,Male
37,43650,185.00,75,786.64,Indiana Jones and the Kingdom of the Crystal S...,5.7,2495,2008,May,Wednesday,Steven Spielberg,Male
47,43666,170.00,32,185.77,Hugo,7.0,2141,2011,Nov,Tuesday,Martin Scorsese,Male
93,43754,140.00,101,268.03,Exodus: Gods and Kings,5.6,1921,2014,Dec,Wednesday,Ridley Scott,Male
105,43772,140.00,44,183.35,The BFG,6.0,1000,2016,Jun,Wednesday,Steven Spielberg,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1427,47934,1.30,58,28.26,Taxi Driver,8.0,2535,1976,Feb,Saturday,Martin Scorsese,Male
1429,47949,0.00,2,0.00,Shine a Light,7.2,44,2008,Feb,Thursday,Martin Scorsese,Male
1453,48294,0.00,6,0.00,She's Gotta Have It,6.1,25,1986,Aug,Friday,Spike Lee,Male
1460,48363,0.00,3,0.32,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,Male
1464,48395,0.22,14,2.04,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
data['director_name'].value_counts()

Steven Spielberg      26
Martin Scorsese       19
Clint Eastwood        19
Woody Allen           18
Ridley Scott          16
                      ..
Tim Hill               5
Jonathan Liebesman     5
Roman Polanski         5
Larry Charles          5
Nicole Holofcener      5
Name: director_name, Length: 199, dtype: int64

split in pandas:

In [ ]:
# Read about split in strings: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.split.html

**size in pandas:**

In [ ]:
import pandas as pd
student_data = pd.DataFrame({
'school_code': ['s001','s002','s003','s001','s002','s004','s001','s003'],
'class': ['V', 'V', 'VI', 'VI', 'V', 'VI','IX','X'],
'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes','Jane','Martin'],
'age': [12, 12, 13, 13, 14, 12, 15, 20],
'height': [173, 192, 186, 167, 151, 159, 140, 160],
'weight': [35, 32, 33, 30, 31, 32, 40, 50]},
 index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6','S7','S8'])

In [ ]:
student_data

   school_code class            name  age  height  weight
S1        s001     V  Alberto Franco   12     173      35
S2        s002     V    Gino Mcneill   12     192      32
S3        s003    VI     Ryan Parkes   13     186      33
S4        s001    VI    Eesha Hinton   13     167      30
S5        s002     V    Gino Mcneill   14     151      31
S6        s004    VI    David Parkes   12     159      32
S7        s001    IX            Jane   15     140      40
S8        s003     X          Martin   20     160      50

In [ ]:
student_data.size # r * c

48

In [ ]:
grouped_data = student_data.groupby(['school_code', 'class'])      
print(grouped_data.size())  # number of rows for each group.
print(grouped_data.count()) # number of values. Here it is based on the groupby.

school_code  class
s001         IX       1
             V        1
             VI       1
s002         V        2
s003         VI       1
             X        1
s004         VI       1
dtype: int64
                   name  age  height  weight
school_code class
s001        IX        1    1       1       1
            V         1    1       1       1
            VI        1    1       1       1
s002        V         2    2       2       2
s003        VI        1    1       1       1
            X         1    1       1       1
s004        VI        1    1       1       1

**groupby.tail: Return last n rows of each group.**

In [ ]:
student_data

   school_code class            name  age  height  weight
S1        s001     V  Alberto Franco   12     173      35
S2        s002     V    Gino Mcneill   12     192      32
S3        s003    VI     Ryan Parkes   13     186      33
S4        s001    VI    Eesha Hinton   13     167      30
S5        s002     V    Gino Mcneill   14     151      31
S6        s004    VI    David Parkes   12     159      32
S7        s001    IX            Jane   15     140      40
S8        s003     X          Martin   20     160      50

In [ ]:
n = 1                                                              
rows_to_drop=student_data.groupby(['school_code']).tail(n).index
print(rows_to_drop)

indexes_to_be_deleted = student_data.groupby(['school_code']).tail(n)
print(indexes_to_be_deleted) 

result_of_drop = student_data.drop(rows_to_drop, axis=0)
print(result_of_drop)

Index(['S5', 'S6', 'S7', 'S8'], dtype='object')
   school_code class          name  age  height  weight
S5        s002     V  Gino Mcneill   14     151      31
S6        s004    VI  David Parkes   12     159      32
S7        s001    IX          Jane   15     140      40
S8        s003     X        Martin   20     160      50
   school_code class            name  age  height  weight
S1        s001     V  Alberto Franco   12     173      35
S2        s002     V    Gino Mcneill   12     192      32
S3        s003    VI     Ryan Parkes   13     186      33
S4        s001    VI    Eesha Hinton   13     167      30